name: Hola Mundo Avelina

on: [push]

jobs:
  uno:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje
        run: |
          echo "Avelina Hernández Hernández - Matrícula: 20210667 - Décimo A"
      - name: Touch File
        run: |
          touch hola.txt
          ls -al
      - name: Set text
        run: |
          echo "Hola mundo" >> hola.txt
          ls -al
      - name: Read File
        run: |
          cat hola.txt

  dos:
    runs-on: ubuntu-latest
    needs: [uno]
    steps:
      - name: Directorio
        run: ls -al
