name: Hola Mundo Avelina

on: [push]

jobs:
  uno:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje
        run: |
          echo "Avelina Hernández Hernández - Matrícula: 20210667 - Décimo A"
      - name: Touch File
        run: |
          touch hola.txt
          ls -al
      - name: Set text
        run: |
          echo "Hola mundo" >> hola.txt
          ls -al
      - name: Read File
        run: |
          cat hola.txt
          ls -al

  dos:
    runs-on: ubuntu-latest
    needs: [uno]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Directorio
        run: ls -al
      - name: instalar
        run: |
          cd .github/workflows
          ls -al
          chmod +x script.sh
          ls -al
